spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://fiapcommerce.mysql.dbaas.com.br:3306/fiapcommerce?createDatabaseIfNotExist=true
        password: abc123456   
        username: fiapcommerce
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411
    rabbitmq:
      host: buck-01.rmq.cloudamqp.com
      port: 5672
      username: bkufqxgt
      password: 97ZXwk6hhRiOyE3S84MGf7aKPU0jVRCw
 
logging:
    level:
        com.netflix: WARN
        org.springframework.web: WARN
        com.thoughtmechanix: DEBUG

eureka:
  client:
    serviceurl:
      defaultzone: http://localhost:8761/eureka/
      
queue:
  order:
    name: PEDIDOS